[package]
name = "ave"
version = "0.1.0-alpha"
authors = ["James Hiew <james@hiew.net>"]

[dependencies]
glium = "0.27.0"
glutin = "0.23.0" 
cgmath = "0.17.0"
collision = "0.20.1"
float-cmp = "0.6.0"
rand = "0.7.3"
log = "0.4.8"
simplelog = "0.7.4"
noise = "0.6.0"
