[package]
name = "ave"
version = "0.1.0-alpha"
authors = ["James Hiew <james@hiew.net>"]

[dependencies]
glium = "0.25.1"
glutin = "0.21.2" 
cgmath = "0.15.0"
collision = "0.20.1"
float-cmp = "0.2.5"
rand = "0.7.3"
log = "0.3.8"
simplelog = "0.3.2"
noise = "0.4.1"
