[package]
name = "ave"
version = "0.1.0-alpha"
authors = ["James Hiew <james@hiew.net>"]

[dependencies]
glium = "0.26.0"
glutin = "0.22.1" #cocoa crate bad
cgmath = "0.15.0"
collision = "0.12.0"
float-cmp = "0.2.5"
rand = "0.3.18"
log = "0.3.8"
simplelog = "0.3.2"
noise = "0.4.1"
